[package]
name = "finn_gen_gen"
version = "0.0.1"
edition = "2018"
authors = ["finn Developers <mimblewimble@lists.launchpad.net>"]
description = "Utility to automate the generation of finn's genesis block"
license = "Apache-2.0"
repository = "https://github.com/mimblewimble/finn"
keywords = [ "crypto", "finn", "mimblewimble" ]
readme = "README.md"

[[bin]]
name = "gen_gen"
path = "src/bin/gen_gen.rs"

[dependencies]
chrono = "0.4.4"
cuckoo_miner = "1.0.0"
curl = "0.4.19"
finn_core = { path = "../../core" }
finn_chain = { path = "../../chain" }
finn_keychain = { path = "../../keychain" }
finn_miner_plugin = "1.0.0"
finn_store = { path = "../../store" }
finn_util = { path = "../../util" }
finn_wallet = { path = "../../wallet" }
rpassword = "2.0.0"
serde_json = "1"

[patch.crates-io]
finn_api = { path = "../../api" }
finn_core = { path = "../../core" }
finn_chain = { path = "../../chain" }
finn_keychain = { path = "../../keychain" }
finn_util = { path = "../../util" }
finn_wallet = { path = "../../wallet" }
